### ISSUE TITLE
Add support for account balances

### ISSUE THREAD

**Issue by cameri** [wxt9861/ynab#16]
I needed support to grab account balances from a budget and it was not available.

I added support in this PR:

https://github.com/wxt9861/ynab/pull/15

I've also corrected a few typos and added documentation of the feature.

**Comment by cameri** [comment]
Is this repo still maintained?

**Comment by rstuke82** [comment]
I would like this feature as well.

**Comment by cameri** [comment]
@Stuke00 I've implemented this on my own fork which you could use until we hear back from @wxt9861 
Here's the link: https://github.com/Cameri/ynab

**Comment by wxt9861** [comment]
Sorry for the delay. Your PR was merged. Thank you for the contribution.

**Comment by cameri** [comment]
Thanks, and welcome back :)
