### ISSUE TITLE
The system cannot restart because the configuration is not valid: Integration error: ynab - Integration 'ynab' not found."

### ISSUE THREAD

**Issue by weimediaacount** [wxt9861/ynab#25]
Homeassistant will not restart following adding ynab to configuation.yaml. The error message is "The system cannot restart because the configuration is not valid: Integration error: ynab - Integration 'ynab' not found."

**Comment by wxt9861** [comment]
Ensure you install the component, then stop/start HASS instead of restart.

**Comment by weimediaacount** [comment]
> Ensure you install the component, then stop/start HASS instead of restart.

I have managed to get it working by doing a restart after downloading the integration, then editing configuration.yaml to include ynab, followed by another restart. 

Thanks.
