### ISSUE TITLE
Pending Transactions for monitored accounts

### ISSUE THREAD

**Issue by guitarwiz09** [wxt9861/ynab#33]
Hi, not as much an issue but a limitation that I'm curious if you could assist with.

I have various credit cards and I manage one and my wife manages the other. It would be awesome to see if there were "need_approval" tagged to each account, so I could script a notification and dashboard to show who needs to go in and update their budget. 

Thanks!

**Comment by wxt9861** [comment]
I am not sure how that would work - this component does not perform any of its own logic at the moment. How do you currently handle this within ynab?

**Comment by wxt9861** [comment]
Closing because stale
